### ISSUE TITLE
There are no title tags in some pages

### ISSUE THREAD

**Issue by Rolikasi** [unicef/publicgoods-website#14]
**Reproduce**
Navigate to [https://digitalpublicgoods.net/](https://digitalpublicgoods.net/) and [https://digitalpublicgoods.net/map/](https://digitalpublicgoods.net/map/). 
You will see url in tab name.

**Expected**
`Digital Public Goods Alliance` for main page and
`DPG map` for map visualization

**Comment by lacabra** [comment]
Thanks @Rolikasi for documenting this.

The page title for https://digitalpublicgoods.net/map/ has been fixed.

The missing page title for the homepage seems to be a shortcoming of the Wordpress theme, thus I'm assigning this to @SarahWat

**Comment by SarahWat** [comment]
Confirming that @lacabra was able to fix the homepage issue.
