### ISSUE TITLE
404 Errors

### ISSUE THREAD

**Issue by starkfire** [unicef/publicgoods-website#4]
The [blog](https://digitalpublicgoods.net/blog/) page returns 404 errors in the console.

![image](https://user-images.githubusercontent.com/26057339/102188508-555a8180-3ef0-11eb-8aca-9f4d5d6379f2.png)

The following lines are causing the errors:
```html
<!-- Enter your scripts here --><link rel='stylesheet' id='themeisle-gutenberg-post-672.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-672.css?ver=1605794293' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-662.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-662.css?ver=1605646713' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-646.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-646.css?ver=1605021459' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-631.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-631.css?ver=1603803121' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-623.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-623.css?ver=1603712780' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-612.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-612.css?ver=1603205209' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-577.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-577.css?ver=1602590297' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-564.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-564.css?ver=1601988238' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-510.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-510.css?ver=1600863176' type='text/css' media='all' />
<link rel='stylesheet' id='themeisle-gutenberg-post-418.css-css'  href='/wp-content/uploads/themeisle-gutenberg/post-418.css?ver=1600727635' type='text/css' media='all' />
```

Other pages are also having the same errors, including this [page](https://digitalpublicgoods.net/who-we-are/). Pages are trying to make a GET request to 'https://digitalpublicgoods.net/wp-includes/js/wp-emoji-release.min.js?ver=5.3.2', which causes the 404.

**Comment by lacabra** [comment]
Thanks again @starkfire for reporting this `404` errors. Much appreciated 🙏
* wp-emoji-release.min.js has been addded in ef08fb5, and that error is gone.

I'm investigating the other errors

**Comment by lacabra** [comment]
It is somewhat ironic because these css files are all empty, they are all 0-byte files. I presume they are in place in case custom styles are to be added, but since I don't expect to use that functionality in the near future, and there is a harder-to-fix issue in tracking these files properly, I have disabled them altogether in 33333ad.

I see no more `404` errors, so I'm closing this issue. 

Thanks again @starkfire for raising up these two issues 🙏
