### ISSUE TITLE
Searchbar in the Blog Page does not work

### ISSUE THREAD

**Issue by starkfire** [unicef/publicgoods-website#5]
The searchbar in the [Blog](https://digitalpublicgoods.net/blog/) page will simply redirect back to the homepage and pass the search input as a parameter.

![image](https://user-images.githubusercontent.com/26057339/102189651-ee3dcc80-3ef1-11eb-9a0d-b644043dbded.png)

![image](https://user-images.githubusercontent.com/26057339/102189701-ff86d900-3ef1-11eb-9eb6-22ae2ecaf82f.png)

**Comment by lacabra** [comment]
Thanks @starkfire for reporting this bug, much appreciated. Interestingly we had spotted this shortcoming some weeks ago and disabled the search functionality, but it was inadvertently re-enabled. Thus it has been disabled for good in 39c72df.
